# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clueDialog.ui'
#
# Created: Fri Apr  3 20:35:06 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_clueDialog(object):
    def setupUi(self, clueDialog):
        clueDialog.setObjectName("clueDialog")
        clueDialog.resize(722, 470)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        clueDialog.setFont(font)
        self.label_4 = QtWidgets.QLabel(clueDialog)
        self.label_4.setGeometry(QtCore.QRect(10, 290, 141, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.descriptionField = QtWidgets.QLineEdit(clueDialog)
        self.descriptionField.setGeometry(QtCore.QRect(160, 171, 551, 39))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.descriptionField.setFont(font)
        self.descriptionField.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.descriptionField.setText("")
        self.descriptionField.setObjectName("descriptionField")
        self.buttonBox = QtWidgets.QDialogButtonBox(clueDialog)
        self.buttonBox.setGeometry(QtCore.QRect(550, 360, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_3 = QtWidgets.QLabel(clueDialog)
        self.label_3.setGeometry(QtCore.QRect(20, 230, 131, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(clueDialog)
        self.label.setGeometry(QtCore.QRect(0, 170, 151, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.instructionsField = QtWidgets.QLineEdit(clueDialog)
        self.instructionsField.setGeometry(QtCore.QRect(160, 290, 551, 40))
        self.instructionsField.setObjectName("instructionsField")
        self.locationField = QtWidgets.QLineEdit(clueDialog)
        self.locationField.setGeometry(QtCore.QRect(160, 230, 551, 39))
        self.locationField.setObjectName("locationField")
        self.label_2 = QtWidgets.QLabel(clueDialog)
        self.label_2.setGeometry(QtCore.QRect(270, 20, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.clueNumberField = QtWidgets.QLineEdit(clueDialog)
        self.clueNumberField.setGeometry(QtCore.QRect(640, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.clueNumberField.setFont(font)
        self.clueNumberField.setObjectName("clueNumberField")
        self.label_6 = QtWidgets.QLabel(clueDialog)
        self.label_6.setGeometry(QtCore.QRect(560, 20, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.groupBox = QtWidgets.QGroupBox(clueDialog)
        self.groupBox.setGeometry(QtCore.QRect(30, 70, 661, 81))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioLocField = QtWidgets.QLineEdit(self.groupBox)
        self.radioLocField.setEnabled(False)
        self.radioLocField.setGeometry(QtCore.QRect(420, 20, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.radioLocField.setFont(font)
        self.radioLocField.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioLocField.setText("")
        self.radioLocField.setObjectName("radioLocField")
        self.callsignField = QtWidgets.QLineEdit(self.groupBox)
        self.callsignField.setEnabled(False)
        self.callsignField.setGeometry(QtCore.QRect(240, 20, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.callsignField.setFont(font)
        self.callsignField.setFocusPolicy(QtCore.Qt.NoFocus)
        self.callsignField.setText("")
        self.callsignField.setObjectName("callsignField")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setEnabled(False)
        self.label_5.setGeometry(QtCore.QRect(240, 40, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setEnabled(False)
        self.label_8.setGeometry(QtCore.QRect(420, 40, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setEnabled(False)
        self.label_7.setGeometry(QtCore.QRect(130, 40, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.timeField = QtWidgets.QLineEdit(self.groupBox)
        self.timeField.setEnabled(False)
        self.timeField.setGeometry(QtCore.QRect(130, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.timeField.setFont(font)
        self.timeField.setFocusPolicy(QtCore.Qt.NoFocus)
        self.timeField.setText("")
        self.timeField.setObjectName("timeField")
        self.dateField = QtWidgets.QLineEdit(self.groupBox)
        self.dateField.setEnabled(False)
        self.dateField.setGeometry(QtCore.QRect(20, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.dateField.setFont(font)
        self.dateField.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dateField.setText("")
        self.dateField.setObjectName("dateField")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setEnabled(False)
        self.label_9.setGeometry(QtCore.QRect(20, 40, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.clueQuickTextButton1 = QtWidgets.QPushButton(clueDialog)
        self.clueQuickTextButton1.setGeometry(QtCore.QRect(20, 350, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.clueQuickTextButton1.setFont(font)
        self.clueQuickTextButton1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.clueQuickTextButton1.setObjectName("clueQuickTextButton1")
        self.clueQuickTextButton3 = QtWidgets.QPushButton(clueDialog)
        self.clueQuickTextButton3.setGeometry(QtCore.QRect(400, 350, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.clueQuickTextButton3.setFont(font)
        self.clueQuickTextButton3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.clueQuickTextButton3.setObjectName("clueQuickTextButton3")
        self.clueQuickTextButton4 = QtWidgets.QPushButton(clueDialog)
        self.clueQuickTextButton4.setGeometry(QtCore.QRect(20, 390, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.clueQuickTextButton4.setFont(font)
        self.clueQuickTextButton4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.clueQuickTextButton4.setObjectName("clueQuickTextButton4")
        self.clueQuickTextButton2 = QtWidgets.QPushButton(clueDialog)
        self.clueQuickTextButton2.setGeometry(QtCore.QRect(200, 350, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.clueQuickTextButton2.setFont(font)
        self.clueQuickTextButton2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.clueQuickTextButton2.setObjectName("clueQuickTextButton2")
        self.clueQuickTextUndoButton = QtWidgets.QPushButton(clueDialog)
        self.clueQuickTextUndoButton.setGeometry(QtCore.QRect(400, 390, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.clueQuickTextUndoButton.setFont(font)
        self.clueQuickTextUndoButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.clueQuickTextUndoButton.setObjectName("clueQuickTextUndoButton")
        self.clueReportPrintCheckBox = QtWidgets.QCheckBox(clueDialog)
        self.clueReportPrintCheckBox.setGeometry(QtCore.QRect(180, 430, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.clueReportPrintCheckBox.setFont(font)
        self.clueReportPrintCheckBox.setChecked(True)
        self.clueReportPrintCheckBox.setObjectName("clueReportPrintCheckBox")
        self.clueQuickTextButton5 = QtWidgets.QPushButton(clueDialog)
        self.clueQuickTextButton5.setGeometry(QtCore.QRect(200, 390, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.clueQuickTextButton5.setFont(font)
        self.clueQuickTextButton5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.clueQuickTextButton5.setObjectName("clueQuickTextButton5")

        self.retranslateUi(clueDialog)
        self.buttonBox.accepted.connect(clueDialog.accept)
        self.buttonBox.rejected.connect(clueDialog.reject)
        self.clueQuickTextButton1.clicked.connect(clueDialog.clueQuickTextAction)
        self.clueQuickTextButton2.clicked.connect(clueDialog.clueQuickTextAction)
        self.clueQuickTextButton3.clicked.connect(clueDialog.clueQuickTextAction)
        self.clueQuickTextButton4.clicked.connect(clueDialog.clueQuickTextAction)
        self.clueQuickTextUndoButton.clicked.connect(clueDialog.clueQuickTextUndo)
        self.clueQuickTextButton5.clicked.connect(clueDialog.clueQuickTextAction)
        QtCore.QMetaObject.connectSlotsByName(clueDialog)
        clueDialog.setTabOrder(self.clueNumberField, self.descriptionField)
        clueDialog.setTabOrder(self.descriptionField, self.locationField)
        clueDialog.setTabOrder(self.locationField, self.instructionsField)
        clueDialog.setTabOrder(self.instructionsField, self.timeField)
        clueDialog.setTabOrder(self.timeField, self.radioLocField)
        clueDialog.setTabOrder(self.radioLocField, self.clueQuickTextButton1)
        clueDialog.setTabOrder(self.clueQuickTextButton1, self.clueQuickTextButton3)
        clueDialog.setTabOrder(self.clueQuickTextButton3, self.clueQuickTextButton4)
        clueDialog.setTabOrder(self.clueQuickTextButton4, self.clueQuickTextButton2)
        clueDialog.setTabOrder(self.clueQuickTextButton2, self.clueQuickTextUndoButton)
        clueDialog.setTabOrder(self.clueQuickTextUndoButton, self.callsignField)

    def retranslateUi(self, clueDialog):
        _translate = QtCore.QCoreApplication.translate
        clueDialog.setWindowTitle(_translate("clueDialog", "Clue Report"))
        self.label_4.setText(_translate("clueDialog", "Instructions"))
        self.label_3.setText(_translate("clueDialog", "Location"))
        self.label.setText(_translate("clueDialog", "Description"))
        self.label_2.setText(_translate("clueDialog", "Clue Report"))
        self.label_6.setText(_translate("clueDialog", "Clue #"))
        self.label_5.setText(_translate("clueDialog", "REPORTED BY"))
        self.label_8.setText(_translate("clueDialog", "RADIO LOCATION"))
        self.label_7.setText(_translate("clueDialog", "TIME"))
        self.label_9.setText(_translate("clueDialog", "DATE"))
        self.clueQuickTextButton1.setText(_translate("clueDialog", "COLLECT  [F1]"))
        self.clueQuickTextButton1.setShortcut(_translate("clueDialog", "F1"))
        self.clueQuickTextButton3.setText(_translate("clueDialog", "DISREGARD  [F3]"))
        self.clueQuickTextButton3.setShortcut(_translate("clueDialog", "F3"))
        self.clueQuickTextButton4.setText(_translate("clueDialog", "HOLD POSITION  [F4]"))
        self.clueQuickTextButton4.setShortcut(_translate("clueDialog", "F4"))
        self.clueQuickTextButton2.setText(_translate("clueDialog", "MARK && LEAVE  [F2]"))
        self.clueQuickTextButton2.setShortcut(_translate("clueDialog", "F2"))
        self.clueQuickTextUndoButton.setText(_translate("clueDialog", "UNDO  [Ctrl+Z]"))
        self.clueQuickTextUndoButton.setShortcut(_translate("clueDialog", "Ctrl+Z"))
        self.clueReportPrintCheckBox.setText(_translate("clueDialog", "Print a Clue Report Form as soon as this clue is saved"))
        self.clueQuickTextButton5.setText(_translate("clueDialog", "PROTECT THE CLUE  [F5]"))
        self.clueQuickTextButton5.setShortcut(_translate("clueDialog", "F5"))

