# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fsSendDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fsSendDialog(object):
    def setupUi(self, fsSendDialog):
        fsSendDialog.setObjectName("fsSendDialog")
        fsSendDialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(fsSendDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(fsSendDialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(70, 60, 232, 173))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label)
        self.fleetField = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fleetField.setText("")
        self.fleetField.setObjectName("fleetField")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.fleetField)
        self.deviceField = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.deviceField.setObjectName("deviceField")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.deviceField)
        self.deviceLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.deviceLabel.setObjectName("deviceLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.deviceLabel)
        self.sendTextRadioButton = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.sendTextRadioButton.setChecked(True)
        self.sendTextRadioButton.setObjectName("sendTextRadioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(fsSendDialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.sendTextRadioButton)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sendTextRadioButton)
        self.pollGPSRadioButton = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.pollGPSRadioButton.setObjectName("pollGPSRadioButton")
        self.buttonGroup.addButton(self.pollGPSRadioButton)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pollGPSRadioButton)
        self.sendToAllCheckbox = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.sendToAllCheckbox.setObjectName("sendToAllCheckbox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sendToAllCheckbox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.messageField = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.messageField.setObjectName("messageField")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.messageField)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(8, QtWidgets.QFormLayout.FieldRole, spacerItem2)

        self.retranslateUi(fsSendDialog)
        self.buttonBox.accepted.connect(fsSendDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(fsSendDialog.reject) # type: ignore
        self.sendTextRadioButton.toggled['bool'].connect(fsSendDialog.functionChanged) # type: ignore
        self.sendToAllCheckbox.toggled['bool'].connect(fsSendDialog.sendAllCheckboxChanged) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(fsSendDialog)

    def retranslateUi(self, fsSendDialog):
        _translate = QtCore.QCoreApplication.translate
        fsSendDialog.setWindowTitle(_translate("fsSendDialog", "FleetSync Send Console"))
        self.label.setText(_translate("fsSendDialog", "Fleet ID"))
        self.deviceLabel.setText(_translate("fsSendDialog", "Device ID(s)"))
        self.sendTextRadioButton.setText(_translate("fsSendDialog", "Send Text Message"))
        self.pollGPSRadioButton.setText(_translate("fsSendDialog", "Get Radio Location"))
        self.sendToAllCheckbox.setText(_translate("fsSendDialog", "Send to All"))
        self.label_3.setText(_translate("fsSendDialog", "Message"))
