# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'options.ui'
#
# Created: Wed Feb  4 21:54:28 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_optionsDialog(object):
    def setupUi(self, optionsDialog):
        optionsDialog.setObjectName("optionsDialog")
        optionsDialog.resize(572, 339)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        optionsDialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(optionsDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.datumField = QtWidgets.QComboBox(optionsDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.datumField.setFont(font)
        self.datumField.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.datumField.setObjectName("datumField")
        self.datumField.addItem("")
        self.datumField.addItem("")
        self.gridLayout.addWidget(self.datumField, 1, 1, 1, 1)
        self.timeoutField = QtWidgets.QSlider(optionsDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.timeoutField.setFont(font)
        self.timeoutField.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.timeoutField.setMinimum(0)
        self.timeoutField.setMaximum(12)
        self.timeoutField.setSingleStep(1)
        self.timeoutField.setPageStep(2)
        self.timeoutField.setProperty("value", 0)
        self.timeoutField.setTracking(True)
        self.timeoutField.setOrientation(QtCore.Qt.Horizontal)
        self.timeoutField.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.timeoutField.setTickInterval(1)
        self.timeoutField.setObjectName("timeoutField")
        self.gridLayout.addWidget(self.timeoutField, 3, 1, 1, 1)
        self.timeoutLabel = QtWidgets.QLabel(optionsDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.timeoutLabel.setFont(font)
        self.timeoutLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeoutLabel.setObjectName("timeoutLabel")
        self.gridLayout.addWidget(self.timeoutLabel, 3, 0, 1, 1)
        self.formatField = QtWidgets.QComboBox(optionsDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.formatField.setFont(font)
        self.formatField.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.formatField.setObjectName("formatField")
        self.formatField.addItem("")
        self.formatField.addItem("")
        self.formatField.addItem("")
        self.formatField.addItem("")
        self.gridLayout.addWidget(self.formatField, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(optionsDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.incidentField = QtWidgets.QLineEdit(optionsDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.incidentField.setFont(font)
        self.incidentField.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.incidentField.setObjectName("incidentField")
        self.gridLayout.addWidget(self.incidentField, 0, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(optionsDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(optionsDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(optionsDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(optionsDialog)
        self.buttonBox.accepted.connect(optionsDialog.accept)
        self.buttonBox.rejected.connect(optionsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(optionsDialog)

    def retranslateUi(self, optionsDialog):
        _translate = QtCore.QCoreApplication.translate
        optionsDialog.setWindowTitle(_translate("optionsDialog", "Options"))
        self.datumField.setItemText(0, _translate("optionsDialog", "NAD27 CONUS"))
        self.datumField.setItemText(1, _translate("optionsDialog", "WGS84"))
        self.timeoutLabel.setText(_translate("optionsDialog", "Timeout"))
        self.formatField.setItemText(0, _translate("optionsDialog", "UTM"))
        self.formatField.setItemText(1, _translate("optionsDialog", "D.d°"))
        self.formatField.setItemText(2, _translate("optionsDialog", "D° M.m\'"))
        self.formatField.setItemText(3, _translate("optionsDialog", "D° M\' S.s\""))
        self.label_4.setText(_translate("optionsDialog", "Coordinate Format"))
        self.incidentField.setText(_translate("optionsDialog", "New Incident"))
        self.label_3.setText(_translate("optionsDialog", "Datum"))
        self.label.setText(_translate("optionsDialog", "Incident Name"))

