# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'printDialog.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_printDialog(object):
    def setupUi(self, printDialog):
        printDialog.setObjectName("printDialog")
        printDialog.resize(356, 271)
        self.layoutWidget = QtWidgets.QWidget(printDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 336, 272))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.buttonBox.setFont(font)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.radioLogField = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.radioLogField.setFont(font)
        self.radioLogField.setIconSize(QtCore.QSize(20, 20))
        self.radioLogField.setChecked(True)
        self.radioLogField.setObjectName("radioLogField")
        self.gridLayout.addWidget(self.radioLogField, 0, 1, 1, 1)
        self.clueLogField = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.clueLogField.setFont(font)
        self.clueLogField.setIconSize(QtCore.QSize(20, 20))
        self.clueLogField.setChecked(True)
        self.clueLogField.setObjectName("clueLogField")
        self.gridLayout.addWidget(self.clueLogField, 2, 1, 1, 1)
        self.teamRadioLogsField = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.teamRadioLogsField.setFont(font)
        self.teamRadioLogsField.setIconSize(QtCore.QSize(20, 20))
        self.teamRadioLogsField.setChecked(True)
        self.teamRadioLogsField.setObjectName("teamRadioLogsField")
        self.gridLayout.addWidget(self.teamRadioLogsField, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.opPeriodComboBox = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opPeriodComboBox.sizePolicy().hasHeightForWidth())
        self.opPeriodComboBox.setSizePolicy(sizePolicy)
        self.opPeriodComboBox.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.opPeriodComboBox.setFont(font)
        self.opPeriodComboBox.setObjectName("opPeriodComboBox")
        self.horizontalLayout.addWidget(self.opPeriodComboBox)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 1)

        self.retranslateUi(printDialog)
        self.buttonBox.accepted.connect(printDialog.accept)
        self.buttonBox.rejected.connect(printDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(printDialog)

    def retranslateUi(self, printDialog):
        _translate = QtCore.QCoreApplication.translate
        printDialog.setWindowTitle(_translate("printDialog", "Print"))
        self.radioLogField.setText(_translate("printDialog", "Radio Log"))
        self.clueLogField.setText(_translate("printDialog", "Clue Log"))
        self.teamRadioLogsField.setText(_translate("printDialog", "Team Radio Logs"))
        self.label.setText(_translate("printDialog", "Select Items to Print"))
        self.label_2.setText(_translate("printDialog", "for Operational Period:"))

