from app.logic.teams import getExtTeamName,getNiceTeamName,getShortNiceTeamName

def test_getExtTeamName():
	assert getExtTeamName("all") == "ALL TEAMS"
	assert getExtTeamName("all units") == "ALL TEAMS"
	assert getExtTeamName("all teams") == "ALL TEAMS"
	assert getExtTeamName("All Teams") == "ALL TEAMS"
	assert getExtTeamName("ALL TEAMS") == "ALL TEAMS"
	assert getExtTeamName("team a") == "teamAlpha"
	assert getExtTeamName("team bravo") == "teamBravo"
	assert getExtTeamName("team 1") == "team00001"
	assert getExtTeamName("team 11") == "team00011"
	assert getExtTeamName("team 101") == "team00101"
	assert getExtTeamName("team 100") == "team00100"
	assert getExtTeamName("t c") == "teamCharlie"
	assert getExtTeamName("t 1") == "team00001"
	assert getExtTeamName("t 101") == "team00101"
	assert getExtTeamName("t1") == "team00001"
	assert getExtTeamName("trans a") == "z_transAlpha"
	assert getExtTeamName("trans bravo") == "z_transBravo"
	assert getExtTeamName("trans 1") == "z_trans00001"
	assert getExtTeamName("trans 11") == "z_trans00011"
	assert getExtTeamName("trans 101") == "z_trans00101"
	assert getExtTeamName("trans 100") == "z_trans00100"
	assert getExtTeamName("a") == "teamAlpha"
	assert getExtTeamName("bravo") == "teamBravo"
	assert getExtTeamName("1") == "team00001"
	assert getExtTeamName("11") == "team00011"
	assert getExtTeamName("101") == "team00101"
	assert getExtTeamName("100") == "team00100"
	assert getExtTeamName(" Team3") == "team00003"
	assert getExtTeamName(" Team400") == "team00400"
	assert getExtTeamName("5") == "team00005"
	assert getExtTeamName("Bravo") == "teamBravo"
	assert getExtTeamName("B") == "teamBravo"
	assert getExtTeamName("t b") == "teamBravo"
	assert getExtTeamName("x") == "teamXray"
	assert getExtTeamName("x1") == "teamXray1"
	assert getExtTeamName("Team 01") == "team00001"
	assert getExtTeamName("Team 101") == "team00101"
	assert getExtTeamName("Team 102") == "team00102"
	assert getExtTeamName("Team 2") == "team00002"
	assert getExtTeamName("Team Charlie") == "teamCharlie"
	assert getExtTeamName("Team02") == "team00002"
	assert getExtTeamName("Team1") == "team00001"
	assert getExtTeamName("TeamAlpha") == "teamAlpha"
	assert getExtTeamName("Transport Bravo") == "z_transportBravo"
	assert getExtTeamName("transportbravo") == "z_transportBravo"
	assert getExtTeamName("transport bravo2") == "z_transportBravo2"
	assert getExtTeamName("Transport1a") == "z_transport00001a"
	assert getExtTeamName("Transport1driver") == "z_transport00001driver"

def test_getNiceTeamName():
	assert getNiceTeamName(getExtTeamName("ALL TEAMS")) == "ALL TEAMS"
	assert getNiceTeamName(getExtTeamName(" Team3")) == "Team 3"
	assert getNiceTeamName(getExtTeamName(" Team400")) == "Team 400"
	assert getNiceTeamName(getExtTeamName("5")) == "Team 5"
	assert getNiceTeamName(getExtTeamName("Bravo")) == "Team Bravo"
	assert getNiceTeamName(getExtTeamName("B")) == "Team Bravo"
	assert getNiceTeamName(getExtTeamName("t b")) == "Team Bravo"
	assert getNiceTeamName(getExtTeamName("t 1")) == "Team 1"
	assert getNiceTeamName(getExtTeamName("t1")) == "Team 1"
	assert getNiceTeamName(getExtTeamName("x")) == "Team Xray"
	assert getNiceTeamName(getExtTeamName("x1")) == "Team Xray1"
	assert getNiceTeamName(getExtTeamName("Team 01")) == "Team 1"
	assert getNiceTeamName(getExtTeamName("Team 101")) == "Team 101"
	assert getNiceTeamName(getExtTeamName("Team 102")) == "Team 102"
	assert getNiceTeamName(getExtTeamName("Team 2")) == "Team 2"
	assert getNiceTeamName(getExtTeamName("Team Charlie")) == "Team Charlie"
	assert getNiceTeamName(getExtTeamName("Team02")) == "Team 2"
	assert getNiceTeamName(getExtTeamName("Team1")) == "Team 1"
	assert getNiceTeamName(getExtTeamName("TeamAlpha")) == "Team Alpha"
	assert getNiceTeamName(getExtTeamName("Transport Bravo")) == "Transport Bravo"
	assert getNiceTeamName(getExtTeamName("transportbravo")) == "Transport Bravo"
	assert getNiceTeamName(getExtTeamName("transport bravo2")) == "Transport Bravo2"
	assert getNiceTeamName(getExtTeamName("Transport1a")) == "Transport 1a"
	assert getNiceTeamName(getExtTeamName("Transport1driver")) == "Transport 1driver"

def test_getShortNiceTeamName():
	assert getShortNiceTeamName(getNiceTeamName(getExtTeamName("ALL TEAMS"))) == "ALL"
	assert getShortNiceTeamName(getNiceTeamName(getExtTeamName(" Team3"))) == "3"
	assert getShortNiceTeamName(getNiceTeamName(getExtTeamName(" Team400"))) == "400"
	assert getShortNiceTeamName(getNiceTeamName(getExtTeamName("5"))) == "5"
	assert getShortNiceTeamName(getNiceTeamName(getExtTeamName("Bravo"))) == "Bravo"
	assert getShortNiceTeamName(getNiceTeamName(getExtTeamName("B"))) == "Bravo"
	assert getShortNiceTeamName(getNiceTeamName(getExtTeamName("t b"))) == "Bravo"
	assert getShortNiceTeamName(getNiceTeamName(getExtTeamName("t 1"))) == "1"
	assert getShortNiceTeamName(getNiceTeamName(getExtTeamName("t1"))) == "1"
	assert getShortNiceTeamName(getNiceTeamName(getExtTeamName("x"))) == "Xray"
	assert getShortNiceTeamName(getNiceTeamName(getExtTeamName("x1"))) == "Xray1"
	assert getShortNiceTeamName(getNiceTeamName(getExtTeamName("Team 01"))) == "1"
	assert getShortNiceTeamName(getNiceTeamName(getExtTeamName("Team 101"))) == "101"
	assert getShortNiceTeamName(getNiceTeamName(getExtTeamName("Team 102"))) == "102"
	assert getShortNiceTeamName(getNiceTeamName(getExtTeamName("Team 2"))) == "2"
	assert getShortNiceTeamName(getNiceTeamName(getExtTeamName("Team Charlie"))) == "Charlie"
	assert getShortNiceTeamName(getNiceTeamName(getExtTeamName("Team02"))) == "2"
	assert getShortNiceTeamName(getNiceTeamName(getExtTeamName("Team1"))) == "1"
	assert getShortNiceTeamName(getNiceTeamName(getExtTeamName("TeamAlpha"))) == "Alpha"
	assert getShortNiceTeamName(getNiceTeamName(getExtTeamName("Transport Bravo"))) == "TransportBravo"
	assert getShortNiceTeamName(getNiceTeamName(getExtTeamName("transportbravo"))) == "TransportBravo"
	assert getShortNiceTeamName(getNiceTeamName(getExtTeamName("transport bravo2"))) == "TransportBravo2"
	assert getShortNiceTeamName(getNiceTeamName(getExtTeamName("Transport1a"))) == "Transport1a"
	assert getShortNiceTeamName(getNiceTeamName(getExtTeamName("Transport1driver"))) == "Transport1driver"
