= Installation

There is currently no installation script or program; here are the steps to complete in sequence:

1. Install python 3.8 or higher - install for All Users, which may require you to run the installer as Administrator, and also to check 'install for all users' in the Advanced Options, and change the installation directory to C:\Python-<version> to avoid spaces in the directory name, but this will require you to edit the properties of Lib\site-packages in the python install directory to remove the read-only flag (and apply to all subdirectories) in order to allow the following steps.

2. Download the zip from this repository, and unzip to C:\

3. Install the required python modules, listed in requirements.txt.
To install them, open a terminal or powershell window in C:\ then use: 

    pip install -r requirements.txt

4. We use PDFtk Free for printing reports as PDFs.
Download and install the free version from (https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/
During install, you will be asked if the pdftk directory should be added to your path; make sure you answer 'yes'.

5. Adobe Acrobat Reader must be installed and must have been run once to initialize itself and to set itself as the default application for pdf viewing; otherwise the terminal will show a win32api error during printing.  
Not sure why this is, but, we found a stackoverflow thread where someone else had the same issue.

6. Make sure the Liberation Sans font is installed through the operating system.
(TBD: from where? acquire the Liberation Sans .ttf file(s), right-click to install).  
You will know if you are missing it when a generated PDF during print will show up with a bunch of dots instead of letters.

== radiolog.cfg optional settings

Optional file local/radiolog.cfg can be used to change various settings.
That file is plain text, and has documentation inside it.

If the 'local' directory does not exist yet, i.e. the first time you run radiolog, it will automatically be created as a copy of the 'local_default' directory included as part of the installation.

If new radiolog versions contain new user-definable options, local_default/radiolog.cfg will contain the new options and documentation.

== radiolog_logo.jpg

You can optionally provide a logo image to be incldued on radiolog printouts (except for clue reports).  
The file will be scaled to print in the pdf files, so a starting size of 200x200 pixels or less should be fine.  
Name the file local/radiolog_logo.jpg.  
Note that a default logo is included in local_default so will be copied in to place the first time you run radiolog.  
You can then delete local/radiolog_logo.jpg or overwrite it with your own logo.

That should do it!
Just run 'python radiolog.py' to run the program.  
You may want to create a desktop shortcut and use the included icon.

