= Installation

Basic installation is done with a self-extracting archive called `radiolog_install_here.exe`.
The only prerequisite is that Adobe Acrobat Reader must be installed and it must have been run at least once.
It must also have been set up as the default application for `.pdf` files. 
(To check this, just find a pdf file and double-click on it. If it comes up in Abode, you're fine. If not, right-click on the PDF file, select `Open with...`, click on "other application", check the boxe that says "always open with this" and then click on Abode Acrobat Reader.)

. Create a folder where you want to install radiolog. For example, `C:\SARStuff`.
. Download the Radiolog installer (`radiolog_install_here.exe`) from https://github.com/ncssar/radiolog.
If your browsers asks you where you want to save it to, tell it to save it to the folder you created above.
If it doesn't ask, then it will probably put in in your Downloads folder.
In that case, move it to the created folder from there.
. Once the installer program is in the desired folder (`C:\SARStuff`), double-click on the installer.
It'll take a minute to run. 
When it's done, you should then have a `radiolog` subfolder in there (`C:\SARStuff\radiolog`).
. Within that folder you should find several dozen files, including the RadioLog program itself (`radiolog.exe`). 
Click on it using the RIGHT mouse button and DRAG it to your desktop. 
Windows should then pop up a small menu with an option to "create a shortcut here." 
Choose that.
From then on, you can double-click on the shortcut to launch RadioLog.

== First-Time Setup

. The first time you run RadioLog, it will ask you to choose your organization. 
Currently, the choices are NCSSAR, RRSAR, and Generic.
That determines how it initializes things.
(More on that in a moment.)
. Next, it will ask you if it should create a folder to store your RadioLog data.
If you say yes, it will do so and carry on.
If you say no (because you don't like the given suggestion for the data location), it will stop running.
In that case, you can change the configuration setting for the name of that folder (again, more on that below) and try again.

That's it. 
At this point, you should be up and running.
Go ahead and give it a test drive.
Make up an incident name and then start making up log entries. 
(Radio checks, teams departing, teams commencing searches, clues found, subject located, ...)
Click the "?" icon at any time for help.

== Adjusting the Configuration

When you selected the name of your organization, RadioLog created a sub-folder called `local` (thus `C:\SARStuff\radiolog\local`) and in there it placed various files that are specific to your organization.
(Or, if you chose Generic, then it just started you out with some default settings.)

At a minimum, it will have created a `radiolog.cfg` file in the `local` folder.
This file contains various settings.
It is a plain text file, and it has documentation inside it.

== radiolog_logo.jpg

The `local` folder will also contain a logo image (probably called `radiolog_logo.jpg`).
This logo is used on all RadioLog printouts (except for clue reports).  
Feel free to replace it with a different logo.
The image will be scaled to print in the pdf files.
A starting size of about 200x200 pixels should be fine.  



== Installing from Source

If you happen to be a Python developer and want to explore the RadioLog source code, then see link:doc_technical/DEVELOPMENT_SETUP.adoc[].


Next Topic: link:/doc_technical/CONTRIBUTING.adoc[Contributing]