= The Automation Tool

In the devtools folder, there is a script called `radiolog_automation.py`.

1. Start RadioLog running
2. Open a separate CMD window.
3. CD to the devtools folder
4. Run radiolog_automation.py
5. Choose between numeric teams (Team 2) or phonetic (Bravo)
6. Click a button and watch a ghost type things into RadioLog for you.


== Updating the Tool

The code is divided into two classes: InspectorWindow(QWidget) and Automator().
InspectorWindow is the tool's dialog box.
Automator does the actual ghostly typing.


=== How to Refer to the Controls in a Dialog

To get a recursive dump of all of the controls within a window, use `<the window>.print_control_identifiers()`



=== (Selected) Methods for Manipulating the Controls

[width="100%",cols="2,4"]
|===
| All Controls  | .print_control_identifiers() -- see above
|               | .type_keys(keystroke notation per below)
|               | .click(), .double_click(), .right_click()
|               | .close()
|               | .minimize(), .maximize(), .restore()
|               | .menu_select()
|               | .move_mouse()
|               | .move_window()
|               | .set_focus()
|               | .is_enabled()
|               | .is_visible()
| Edit (text)   | .set_edit_text(text)
|               | .get_line()
|               | .line_count()
|               | .line_length()
|               | .select()
|               | .selection_indices()
|               | .set_window_text()
|               | .text_block()
| CheckBox      | .click() -- there is no .check/.uncheck
| ComboBox      | .item_count()
|               | .item_data()
|               | .item_texts()
|               | .select()
|               | .selected_index()
| Tabs          | .get_selected_tab()
|               | .get_tab_state()
|               | .get_tab_text()
|               | .row_count()
|               | .select()
|               | .tab_count()
|               | .tab_states()
|===

=== KeyStroke Codes (for use with .type_keys() )

[width="100%",cols="2,4,4,2",options="header"]
|===
| Group
| Normal Typing
| Particular Keys
| Notes

| Shift Keys
| {CAPSLOCK}/{CAP}, {VK_SHIFT}, {VK_CONTROL}, {VK_MENU}, {LWIN}, {RWIN}, {RMENU}
| {VK_LSHIFT}, {VK_RSHIFT}, {VK_LMENU}, {VK_LCONTROL}, {VK_RCONTROL}, {VK_RWIN}, {VK_RMENU}
| + == {VK_SHIFT}, ^ == {VK_CONTROL}, % == {VK_MENU} a.k.a. Alt key

| Top Row
| {ESC}, {SCROLLLOCK}, {BREAK}, {PRTSC}, {F1} thru {F24}
| {VK_ESCAPE}, {VK_SCROLL}, {VK_PAUSE}, {VK_PRINT}, {VK_F1} thru {VK_F24}
|

| Number Pad
|
| {NUMLOCK}, {VK_NUMLOCK}, {VK_DIVIDE}, {VK_MULTIPLY}, {VK_SUBTRACT}, {VK_ADD}, {VK_DECIMAL}, {VK_NUMPAD0} thru {VK_NUMPAD9}
|

| Regular Text
| A-Z, a-z, 0-9, (most punctuation)
|
| For a caret, use +6 (shift 6). For a tilde, use +`. For a plus sign, use +=, for a percent-sign use +5.

| Editing
| {SPACE}, {TAB}, {ENTER}, {INSERT}/{INS}, {BACKSPACE}/{BACK}/{BKSP}/{BS}, {DELETE}/{DEL}
| {VK_SPACE}, {VK_TAB}, {VK_RETURN}, {VK_INSERT}, {VK_BACK}, {VK_DELETE}
| ~ is a shortcut for {ENTER}

| Cursor Movement
| {UP}, {DOWN}, {LEFT}, {RIGHT}, {HOME}, {END}, {PGUP}, {PGDN}
| {VK_UP}, {VK_DOWN}, {VK_LEFT}, {VK_RIGHT}, {VK_HOME}, {VK_END}, {VK_PGUP}, {VK_PGDN}
|

| Mouse
|
| {VK_LBUTTON}, {VK_RBUTTON}, {VK_MBUTTON}
|

| Media Controls
|
| {VK_PLAY}, {VK_NEXT}, {VK_PRIOR}
|

| Foreign Language (?)
|
| {VK_CRSEL}, {VK_EREOF}, {VK_EXSEL}, {VK_HANGEUL}, {VK_HANGUL}, {VK_HANJA}, {VK_JUNJA}, {VK_KANA}, {VK_KANJI}
|

| (Unknown)
| {HELP}, {ZOOM}
| {VK_ACCEPT}, {VK_APPS}, {VK_ATTN}, {VK_CANCEL}, {VK_CAPITAL}, {VK_CLEAR}, {VK_CONVERT}, {VK_EXECUTE}, {VK_FINAL}, {VK_HELP}, {VK_MODECHANGE}, {VK_NONAME}, {VK_NONCONVERT}, {VK_OEM_CLEAR}, {VK_PA1}, {VK_PROCESSKEY}, {VK_SELECT}, {VK_SEPARATOR}, {VK_SNAPSHOT}
|

|===


== The RadioLog Dialogs


[width="100%",cols="4,2,2",options="header"]
|===
| Window/Dialog                       | Class Name             | Magic Name
| Radio Log (main window)             | MyWindow               | r.RadioLog
| Radio Log - New Entry               | newEntryWindow         | r.NewEntry
| Clue Report                         | clueDialog             | r.ClueReport
| Clue Report                         | nonRadioClueDialog     | r.ClueReport
| Clue Log                            | clueLogDialog          | r.ClueLog
| Subject Located                     | subjectLocatedDialog   | r.SubjectLocated
| Print                               | printDialog            | r.Print
| Radio Log - FleetSync Filter Setup  | fsFilterDialog         | r.RadioLogFleetSyncFilterSetup
| Change Operational Period           | opPeriodDialog         | r.ChangeOperationalPeriod
| Options                             | optionsDialog          | r.Options
| Help                                | helpWindow             | r.Help
|===

=== Radio Log (class = MyWindow)

[source, Python]
----
r = pywinauto.application.Application(backend="uia").connect(title_re="Radio Log", class_name="MyWindow")
dlg = r.RadioLog

dlg.type_keys("f") # Invoke the New Entry form (by way of the "From" shortcut key)
dlg.child_window(auto_id="Dialog.pushButton", control_type="Button").click()  # Another way to invoke Add Entry

dlg.NonRadioClue.click() # Invoke the non-radio clue form (by clicking on the non-radio clue button)
dlg.child_window(auto_id="Dialog.addNonRadioClueButton", control_type="Button").click()  # Another way to invoke the non-radio clue form

dlg.child_window(auto_id="Dialog.comPortLayoutWidget.fsCheckBox", control_type="CheckBox").click()  # Toggle FS usage
dlg.child_window(auto_id="Dialog.opPeriodButton", control_type="Button").click()  # Invoke the form that bumps to a new operational period
dlg.child_window(auto_id="Dialog.clueLogButton", control_type="Button").click()  #  Open the clue log window
dlg.child_window(auto_id="Dialog.helpButton", control_type="Button").click() #  Open the help window
dlg.child_window(auto_id="Dialog.optionsButton", control_type="Button").click()  #  Open the options window (e.g. Incident name)
dlg.child_window(auto_id="Dialog.fsFilterButton", control_type="Button").click()  # Invoke filtering of the FS data
dlg.child_window(auto_id="Dialog.printButton", control_type="Button").click() # Open the print dialog

dlg.close() # Invokes the Print dialog (if there's anything to print)
dlg.maximize()
dlg.minimize()
dlg.restore()

----


=== Radio Log - New Entry (class = newEntryWindow)

[source, Python]
----
dlg = r.NewEntry

PREFIX = "newEntryWindow.tabWidget.qt_tabwidget_stackedwidget.newEntryWidget"

dlg.child_window(auto_id=PREFIX + ".to_fromField", control_type="ComboBox")
dlg.child_window(auto_id=PREFIX + ".teamField", control_type="Edit")
dlg.child_window(auto_id=PREFIX + ".messageField", control_type="Edit")
dlg.child_window(auto_id=PREFIX + ".teamComboBox", control_type="ComboBox")
dlg.child_window(auto_id=PREFIX + ".radioLocField", control_type="Edit")
dlg.child_window(auto_id=PREFIX + ".relayedCheckBox", control_type="CheckBox")
dlg.child_window(auto_id=PREFIX + ".relayedByComboBox", control_type="ComboBox")
dlg.child_window(auto_id=PREFIX + ".timeField", control_type="Edit")

dlg.type_keys("{F1}")  # [F1] DEPARTING IC
dlg.type_keys("{F2}")  # [F2] STARTING ASSIGNMENT
dlg.type_keys("{F3}")  # [F3] COMPLETED ASSIGNMENT
dlg.type_keys("{F4}")  # [F4] ENROUTE TO IC
dlg.type_keys("{F5}")  # [F5] REQUESTING TRANSPORT
dlg.type_keys("{F6}")  # [F6] AT IC
dlg.type_keys("{F7}")  # [F7] RADIO CHECK: OK
dlg.type_keys("{F8}")  # [F8] WELFARE CHECK: OK
dlg.type_keys("{F9}")  # [F9] STANDBY
dlg.type_keys("{F10}")  # [F10] LOCATED A CLUE
dlg.type_keys("{F11}")  # [F11] SUBJECT LOCATED
dlg.type_keys("{F12}")  # [F12] REQUESTING DEPUTY

dlg.child_window(auto_id=PREFIX + ".statusGroupBox.at_icField", control_type="RadioButton")
dlg.child_window(auto_id=PREFIX + ".statusGroupBox.availableField", control_type="RadioButton")
dlg.child_window(auto_id=PREFIX + ".statusGroupBox.availableField_2", control_type="RadioButton")
dlg.child_window(auto_id=PREFIX + ".statusGroupBox.in_transitField", control_type="RadioButton")
dlg.child_window(auto_id=PREFIX + ".statusGroupBox.standbyField", control_type="RadioButton")
dlg.child_window(auto_id=PREFIX + ".statusGroupBox.waitingForTransportField", control_type="RadioButton")
dlg.child_window(auto_id=PREFIX + ".statusGroupBox.workingField", control_type="RadioButton")

dlg.OK.click() # same as dlg.type_keys("{ENTER}")
dlg.Cancel.click()
dlg.Close.click()
----


=== Clue Report (class = clueDialog)

[source, Python]
----
dlg = r.ClueReport

dlg.child_window(auto_id="clueDialog.descriptionField", control_type="Edit")
dlg.child_window(auto_id="clueDialog.groupBox.radioLocField", control_type="Edit")
dlg.child_window(auto_id="clueDialog.instructionsField", control_type="Edit")
dlg.child_window(auto_id="clueDialog.locationField", control_type="Edit")
dlg.child_window(auto_id="clueDialog.groupBox.timeField", control_type="Edit")
dlg.child_window(auto_id="clueDialog.groupBox.dateField", control_type="Edit")
dlg.child_window(auto_id="clueDialog.clueNumberField", control_type="Edit")
dlg.child_window(auto_id="clueDialog.groupBox.callsignField", control_type="Edit")
dlg.child_window(auto_id="clueDialog.clueReportPrintCheckBox", control_type="CheckBox")

dlg.type_keys("{F1}")    # [F1] COLLECT
dlg.type_keys("{F2}")    # [F2] MARK & LEAVE
dlg.type_keys("{F3}")    # [F3] DISREGARD
dlg.type_keys("{F4}")    # [F4] HOLD POSITION
dlg.type_keys("{F5}")    # [F5] PROTECT THE CLUE
dlg.type_keys("{F6}")    # [F6] STANDBY

dlg.OK.click() # same as dlg.type_keys("{ENTER}")
dlg.Cancel.click()
dlg.Close.click()
----


=== Clue Report (class = nonRadioClueDialog)

[source, Python]
----
WIDGET = ""
----


=== Clue Log (class = clueLogDialog)

[source, Python]
----
dlg = r.ClueLog

dlg.child_window(title="Clue Log", auto_id="clueLogDialog", control_type="Window")
dlg.child_window(title="Context help", control_type="Button")
dlg.child_window(title="Close", control_type="Button")
dlg.child_window(title="Add Non-Radio Clue", auto_id="clueLogDialog.addNonRadioClueButton", control_type="Button")
dlg.child_window(auto_id="clueLogDialog.printButton", control_type="Button")

----


=== Subject Located (class = subjectLocatedDialog)

[source, Python]
----
dlg = r.SubjectLocated

dlg.child_window(title="Subject Located", auto_id="subjectLocatedDialog", control_type="Window")
dlg.child_window(title="Close", control_type="Button")
dlg.child_window(auto_id="subjectLocatedDialog.groupBox.callsignField", control_type="Edit")
dlg.child_window(auto_id="subjectLocatedDialog.groupBox.timeField", control_type="Edit")
dlg.child_window(auto_id="subjectLocatedDialog.groupBox.dateField", control_type="Edit")
dlg.child_window(auto_id="subjectLocatedDialog.groupBox.radioLocField", control_type="Edit")
dlg.child_window(title="OK", control_type="Button")
dlg.child_window(title="Cancel", control_type="Button")
dlg.child_window(auto_id="subjectLocatedDialog.locationField", control_type="Edit")
dlg.child_window(auto_id="subjectLocatedDialog.conditionField", control_type="Edit")
dlg.child_window(auto_id="subjectLocatedDialog.resourcesField", control_type="Edit")
dlg.child_window(auto_id="subjectLocatedDialog.otherField", control_type="Edit")

----


=== Print (class = printDialog)

[source, Python]
----
dlg = r.Print

dlg.child_window(title="Print", auto_id="printDialog", control_type="Window")
dlg.child_window(title="Close", control_type="Button")
dlg.child_window(title="Ok", control_type="Button")
dlg.child_window(title="Cancel", control_type="Button")
dlg.child_window(title="Radio Log", auto_id="printDialog.layoutWidget.radioLogField", control_type="CheckBox")
dlg.child_window(title="Clue Log", auto_id="printDialog.layoutWidget.clueLogField", control_type="CheckBox")
dlg.child_window(title="Team Radio Logs", auto_id="printDialog.layoutWidget.teamRadioLogsField", control_type="CheckBox")
dlg.child_window(auto_id="printDialog.layoutWidget.opPeriodComboBox", control_type="ComboBox")
----


=== Radio Log - FleetSync Filter Setup (class = fsFilterDialog)

[source, Python]
----
dlg = r.RadioLogFleetSyncFilterSetup

dlg.child_window(title="Radio Log - FleetSync Filter Setup", auto_id="fsFilterDialog", control_type="Window")
dlg.child_window(title="Close", control_type="Button")
----


=== Change Operational Period (class = opPeriodDialog)

[source, Python]
----
dlg = r.ChangeOperationalPeriod

dlg.child_window(title="Change Operational Period", auto_id="opPeriodDialog", control_type="Window")
dlg.child_window(title="Close", control_type="Button")
dlg.child_window(title="2", auto_id="opPeriodDialog.newOpPeriodField", control_type="Edit")
dlg.child_window(title="1", auto_id="opPeriodDialog.currentOpPeriodField", control_type="Edit")
dlg.child_window(title="Hide Team Tabs for teams whose status is 'At IC'", auto_id="opPeriodDialog.deleteTabsCheckBox", control_type="CheckBox")
dlg.child_window(title="Print current operational period logs first", auto_id="opPeriodDialog.printCheckBox", control_type="CheckBox")
dlg.child_window(title="OK", control_type="Button")
dlg.child_window(title="Cancel", control_type="Button")
----


=== Options (class = optionsDialog)

[source, Python]
----
dlg = r.Options

dlg.child_window(title="Options", auto_id="optionsDialog", control_type="Window")
dlg.child_window(title="Close", control_type="Button")
dlg.child_window(auto_id="optionsDialog.datumField", control_type="ComboBox")
dlg.child_window(auto_id="optionsDialog.timeoutField", control_type="Slider")
dlg.child_window(auto_id="optionsDialog.buttonBox", control_type="Group")
dlg.child_window(title="OK", control_type="Button")
dlg.child_window(title="Cancel", control_type="Button")
dlg.child_window(auto_id="optionsDialog.formatField", control_type="ComboBox")
dlg.child_window(title="New Incident", auto_id="optionsDialog.incidentField", control_type="Edit")
dlg.child_window(title="Use Second Working Directory", auto_id="optionsDialog.secondWorkingDirCheckBox", control_type="CheckBox")
----


=== Help (class = helpWindow)

[source, Python]
----
dlg = r.Help

dlg.child_window(title="Close", control_type="Button")
----


Next Topic: link:/doc_technical/DESIGN_NOTES.adoc[Design Notes]