= Contributing

== The GitHub Repository

1. While this code has been in use for a few years, and was intended to be open source from the start, it wasn't placed on GitHub until late 2016. 

2. Issues are categorized by topic using Milestones. In the Issues page, hit the Milestones tab to see all the categories and view the issues within one of those Milestones.

3. Relevant issue labels:
 * 'help wanted': if this label is present, we're actively asking for help; if not, the issue is not really ready for outside help and would just cause confusion.  So - if you're looking to contribute, please don't pay much or any attention unless the 'help wanted' label is present.
 * 'enhancement' or 'bug': one of these should be present on all open and active tickets.  Hopefully self-explanatory, let me know if anything is unclear.
 * 'Priority:Low|Medium|High': also hopefully self-explanatory.  The entire set of issues is a "wish list"; the Priority label indicates how useful a resolution of that particular issue would be to the SAR team.

4. If you plan to work on an issue, please assign it to yourself, so that others will know not to start work on the same issue from scratch.

Some issue search and sort shortcuts -- from any of these, you can further refine your search with the Labels and Milestones pull-down menus:

- link:https://github.com/ncssar/radiolog/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22help%20wanted%22[All open help-wanted issues] 
- link:https://github.com/ncssar/radiolog/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22help%20wanted%22%20label%3A%22enhancement%22[All open help-wanted enhancements]
- link:https://github.com/ncssar/radiolog/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22help%20wanted%22%20label%3A%22bug%22[All open help-wanted bugs]
- link:https://github.com/ncssar/radiolog/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22help%20wanted%22%20label%3A%22enhancement%22%20label%3A%22Priority%3AHigh%22[High-priority open help-wanted enhancements]
- link:https://github.com/ncssar/radiolog/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22help%20wanted%22%20label%3A%22bug%22%20label%3A%22Priority%3AHigh%22[High-priority open help-wanted bugs]

Thanks for all your help; happy coding. 
Let us know if you have any questions!

