= Notes on how RadioLog was designed and coded

== Key Sequence Behavior

When the main radio-log form has focus:

*  Pressing `f` or the space bar -- opens a new entry dialog box with these default values: Message "From", first team in team combo box, and the curent time. Focus goes to team field.
*  Pressing `t` -- opens a new entry dialog box with these default values: Message "To", first team in team combo box, and the curent time. Focus goes to team field.
* Pressing any number -- opens a new entry dialog box with these default values: Message "From", first team in team field whose first digit matches the typed number, or, new team# if none match, and the curent time. Focus goes to team field.

When a new-entry dialog box has focus:

* (TBD)

== Message Queue / Stack Rules

When an incoming message happens during editing of an existing message:

 1. add a stack entry on top of the stack and start flashing
 2. if the current message has had no keystrokes / activity in the last n seconds,
      leave it as is and move to the new entry
 3. if the current message has had activity in the last n seconds, leave it open

When message is accepted:

 1. go to next message upwards in the stack
 2. if none, go the next message downwards in the stack
 3. if none, close the dialog

Every n seconds of inactivity:

 1. accept the top message on the stack, and move to the next one

When any given message is set active:

 1. stop flashing, if it was flashing


== Ancillary files shipped with and/or referenced by this code:

- radiolog_logo.jpg - if the logo exists it is included in the printout
- radiolog_rc.txt - resource file, keeps track of last used window geometry and font size
- radiolog_fleetsync.csv - default CSV lookup table: fleet,device,callsign
  (any fleet/device pairs that do not exist in that file will have callsign KW-<fleet>-<device>)

== Files generated by this code:

NOTE: this program uses two working directories for redundancy.
The first one is the current Windows user's Documents directory, and must be writable to avoid a fatal error.
The second one will be written to on every new entry if it is available, but will not cause any error if it is unavailable.
The second working directory is specified below with the variable 'secondWorkingDir'.

- <incident_name>_<timestamp>.csv - CSV of entire radio log, written after each new entry
- <incident_name>_<timestamp>_fleetsync.csv - CSV FleetSync lookup table, written on each callsign change
- <incident_name>_<timestamp>_clueLog.csv - CSV clue log, written after each clue entry
- <incident_name>_<timestamp>_OP#.pdf - PDF of the radio log for specified operational period
- <incident_name>_<timestamp>_clueLog_OP#.pdf - PDF of the clue log for specified operational period
- <incident_name>_<timestamp>_clue##.fdf - FDF of clue report form (see calls to forge_fdf)
- <incident_name>_<timestamp>_clue##.fdf - PDF of clue report form

NOTE: Upon change of incident name, previously saved files are not deleted, but are kept in place as another backup.
Also, the previous log file is copied as the new log file, so that file append on each new entry can continue seamlessly.

== Performance Notes

Once the table length gets about 500 rows or so, some delay is noticable when performing the following actions:

- font resize (+/- keys)
- new entry form closed with 'OK' or Enter/Return, until the new entry appears in the table
- window resize
- print (delay per page)

Conclusions from benchmarking and speed tests on a table of around 1300 rows:

- the single biggest source of delay can be header resize modes:
  ...verticalHeader().setSectionResizeMode(QHeaderView.ResizeToContents)
  will cause each row to resize whenever the contents change, which is probably
  more often than you want, and will be called in a hidden / nested manner
  inside other table view changes.  So, disable any lines like this, and only
  resize when you really need to.  Removing this line reduced redraw time
  on font change from 12 seconds to 3.  Also, it 'completely' eliminates
  window resize delay.

- delay on entry form close is 'eliminated' / deferred by doing all the
  redisplay work in a singleshot after the form is closed

