= Notes on Setting Up a Development Environment

== Using Visual Studio Code (Windows, Mac OS, or Linux)

Microsoft Visual Studio Code (I'll call it VSC from now on) is a free IDE (integrated development environment) that runs on Windows, Mac OS, and Linux.

NOTE: "Visual Studio Code" is different than full-fledged "Visual Studio." VSC is slimmed down. You can work on Python code in either, but VSC is preferred.

Official documentation on editing Python with VSC is at: https://code.visualstudio.com/docs/languages/python. Here is a bare-bones summary:

. Install Python, if not already.
. Download VSC from https://code.visualstudio.com/ and install.
. In the Welcome tab...
. Under Help, click on "Printable keyboard cheatsheet" and print it.
. Under Customize, click on "Tools and Languages"
. Select Python and click Install.
. Open the Command Palette (Ctrl-Shift-P) and type "py" to jump down to the Python commands. Scroll down to "Python: Select Interpreter" and hit enter. It will take a second to find all versions of Python installed on your machine. Select the one you want to use. (If there is only one, it will automatically select it for you.)
. Unit Testing for Python in VSC is disabled by default. To enable testing, open the Command Palette and use "Python: Configure Tests". Select PyTest as the framework, then tell it that the unit tests are in the "tests" folder (not unit_test, not test_data).


. To open the RadioLog project, use File | Open Folder and select the root folder for the project (where you cloned it to).
. To run RadioLog, select radiolog.py and click the run button on the left (Ctrl-Shift-D).
. The first time you open the Run view, it will suggest that you "create a launch.json file." Go ahead and click on that suggestion. Select Python, then select "Python: Current File." A tab will open up with a 14 line default configuration. Just save it as is and close the tab.
. To actually run the program, click on the green "play" button in the upper left.
. The first time you run a Python program, VSC will prompt you to install Linter. Go ahead and install it.



== Running the Unit Tests

We use the new PyTest library for unit testing (not to be confused with PyUnit, the original unit testing library that's part of Python).

Running all of the unit tests from the command line:

    pytest 

Running a specific unit test from the command line:

    pytest tests/test_x.py

Running the unit tests from within Visual Studio Code (VSC):

. (See above for how to configure PyTest in VSC.)
. Click on the flask icon (far left) to bring up the Test Explorer.
. Click on the green double-play icon at the top to rubn all of the tests.
. Or, navigate to a particular test and click the green play icon to the right of it.

See the PyTest documentation for how to write the tests: https://docs.pytest.org/en/latest/


== Using the Debug Logs

TBD

