= Notes on Setting Up a Development Environment

== Installing the radiolog source code

See link:../doc/INSTALL.adoc[INSTALL]

== Installing Visual Studio Code (Windows, Mac OS, or Linux), if desired

Microsoft Visual Studio Code (we'll call it VSCode from now on) is a free IDE (integrated development environment) that runs on Windows, Mac OS, and Linux.

NOTE: "Visual Studio Code" is different than full-fledged "Visual Studio." 
VSCode is slimmed down. 
You can work on Python code in either, but VSCode is preferred.

NOTE: At some point after getting started, be sure to see our link:VSCODE_TIPS.adoc[VSCODE_TIPS]

Official documentation on editing Python with VSCode is at: https://code.visualstudio.com/docs/languages/python. 
Here is a bare-bones summary:

. Install Python, if not already. (TIP: The Python installer defaults to placing it in your user-folder's appdata subfolder. You'll save yourself a world of hurt if you change it to something simpler, e.g. C:\Python38).
. Download VSCode from https://code.visualstudio.com/ and install.
. In the Welcome tab...
. Under Help, click on "Printable keyboard cheatsheet" and print it.
. Under Customize, click on "Tools and Languages"
. Select Python and click Install.
. Open the Command Palette (Ctrl-Shift-P) and type "py" to jump down to the Python commands. Scroll down to "Python: Select Interpreter" and hit enter. It will take a second to find all versions of Python installed on your machine. Select the one you want to use. (If there is only one, it will automatically select it for you.)
. Unit Testing for Python in VSCode is disabled by default. To enable testing, open the Command Palette and use "Python: Configure Tests". Select PyTest as the framework, then tell it that the unit tests are in the "tests" folder (not test_data).
. Open the Command Palette (Ctrl-Shift-P) and type "pref" to jump down to the preferences. Scroll down to "Preferences: Configure Language Specific Settings" and hit enter. Select Python. This will open your settings.json file and add a [Python] section. Start typing "indent" until editor.detectIndentation is selected. Hit enter. From now on, when you open a file in VSCode, it will scan to see if the file uses tabs or spaces and then continue in whatever style it finds.

== Using Visual Studio Code with RadioLog

. To open the RadioLog project, use File | Open Folder and select the root folder for the project (where you cloned it to).
. To run RadioLog, select radiolog.py and click the run button on the left (Ctrl-Shift-D).
. The first time you open the Run view, it will suggest that you "create a launch.json file." Go ahead and click on that suggestion. Select Python, then select "Python: Current File." A tab will open up with a 14 line default configuration. Just save it as is and close the tab.
. To actually run the program, click on the green "play" button in the upper left.
. The first time you run a Python program, VSCode will prompt you to install Linter. Go ahead and install it.


== User Interface

This project uses PyQT5 for the user-interface.
The source for the UI elements (forms, dialog boxes, etc.) are stored in .ui files (with resource information, if any, stored in a corresponding .rc file). 

QT Designer (designer.exe) is the tool that creates the ui files.
To install QT Designer, use:

    pip install pyqt5_tools 

Now, find where it got installed (e.g. C:\Python38\Lib\site-packages\pyqt5_tools\Qt\bin) and create a shortcut to the designer.exe app.
You can use designer.exe to edit an existing .ui file, or create a new one.

Every time you save changes to a .ui file, you then need to convert it to Python code.
The following command generates the corresponding python code:

    pyuic5 -x file.ui -o file_ui.py

In VSCode, there are several plugins for QT. 
It looks like the best option for now is "Qt for Python" by Sean Wu.
The plugin has 7 configuration settings.
Of those, you'll need to set 3 of them:

Designer:

   C:\Python38\Lib\site-packages\pyqt5_tools\Qt\bin\designer.exe (for example)
        (or if you prefer to use QTCreator)
   C:\Qt\Tools\QtCreator\bin\qtcreator.exe

Pyuic:

    pyuic5.exe -d -o ./"${fileBasenameNoExtension}_ui.py"

Pyrcc:
    
    pyrcc5.exe -o ./"${fileBasenameNoExtension}_rc.py"

NOTES: 

. Be sure to use quotes around any path that contains a space.
. Be sure to notice that for this project we add "_rc" and "_ui" before the .py extension for the output files.
. Make sure that your Python Scripts folder (C:\Python38\Scripts) is in the PATH.



== Report Output

Reports are generated by taking a fillable PDF file and populating the fields 

To create the fillable PDF, start with a document file (e.g. clueReportFillable.odt) and use LibreOffice's Form tools to 'Export as PDF'.

(More TBD)

== Running the Unit Tests

We use the new PyTest library for unit testing (not to be confused with PyUnit, the original unit testing library that's part of Python).

    pip install pytest

Running all of the unit tests from the command line:

    pytest 

Running a specific unit test from the command line:

    pytest tests/test_x.py

Running the unit tests from within Visual Studio Code (VSCode):

. (The VSCode install instructions above include how to configure it for PyTest.)
. Click on the flask icon (far left) to bring up the Test Explorer.
. Click on the green circular arrow (refresh) icon at the top to discover all of the tests.
. Click on the green double-play icon at the top to run all of the tests.
. Or, navigate to a particular test and click the green play icon to the right of it.

See the PyTest documentation for how to write the tests: https://docs.pytest.org/en/latest/


== Using the Debug Logs

(TBD)

