[RadioLog]

# This is the RadioLog local configuration file.

# Customize this file for your team's needs; the
#  rest of the published radiolog code should not
#  change from team to team.

# This file will be read from:
#   ${appConfigLocation}
#  where <radiolog> is the main RadioLog install path
#   which contains radiolog.py

# - the first line of this file must be [RadioLog]
# - blank lines and lines that start with a pound
#    sign (#) are ignored
# - do not use quotes around strings in this file
# - default values (the values that will be used
#    by radiolog if this file does not set the value)
#    are described in comments below
# - to set a different value, uncomment the setting
#    line and set its value as needed; incorrect
#    or invalid values will be flagged with warnings
#    or errors when RadioLog is started

##################################################

# agencyName
# - appears on printed radio log and clue forms
# - default: Search and Rescue
#agencyName=Search and Rescue

# datum
# - valid datums: WGS84, NAD27 CONUS, NAD27 (same as NAD27 CONUS)
# - default: WGS84
#datum=WGS84

# coordFormat
# - used for display of all GPS radio coordinates;
#    this setting cannot currently be changed while
#    radiolog is running
# - valid formats: UTM 7x7, UTM 5x5, D.d, DM.m, DMS.s
# - default: UTM 5x5
#coordFormat=UTM 5x5

# timeoutMinutes
# - initial timeout interval
# - valid values are 10 minute intervals, from 10 to 120
# - default: 30
#timeoutMinutes=30

# firstWorkingDir
# - required first working directory, where all
#    radiolog data files will be saved
# - radiolog will abort if this directory is not
#    writable
# - default: ~/Documents
#firstWorkingDir=~/Documents

# secondWorkingDir
# - optional second working directory
# - intended as another form of redundancy and backup
# - all of the same files written to the first working
#    directory will also be written to the second
#    working directory, including rotating backups
# - default: None
#secondWorkingDir=E:\

# logo
# - filename of logo to include in printed forms
# - path is relative to ${appDataLocation}
# - default: radiolog_logo.jpg
#logo=radiolog_logo.jpg

# server
# - node name of CalTopo Desktop server; http get requests will
#    be sent to this server for every incoming set of
#    radio coordinates
# - default: localhost
#server=localhost

# tabGroups
# - optional team tabs grouping by callsign using regular expressions
# - callsigns that do not match any regular expression will be part of
#     a separate 'unmatched' tab group
# - tab groups will be separated by a small gap
# - specify a list of lists, in python syntax
# - groups will be shown from left-to-right in the same order as specified
# - first element of each inner list is the tab group name for reference
#     (this is not actually displayed anywhere)
# - second element of each inner list is a regular expression string;
#     callsigns matching this group's regular expression will be part
#     of this group
# - default: [["Numbers","^Team [0-9]+"]] meaning that all Team # tabs
#     will be part of one group, and all other callsigns will be part of
#     a different group, separated from the first group's tabs by a gap
# EXAMPLE: tabGroups=[["NCSOcmd","^1[sel][0-9]+"],["NCSO","^1[tpndovg][0-9]+"],["NCPD","^2[atpnsdelovg][0-9]+"],["TPD","^3[atpnsdelovg][0-9]+"],["GVPD","^4[atpnsdelovg][0-9]+"],["CHP","^22s[0-9]+"],["Numbers","^Team [0-9]+"]]
#tabGroups=[["Numbers","^Team [0-9]+"]]

# continuedIncidentWindowDays

# continuedIncidentWindowDays = 4
