# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\continuedIncidentDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_continuedIncidentDialog(object):
    def setupUi(self, continuedIncidentDialog):
        continuedIncidentDialog.setObjectName("continuedIncidentDialog")
        continuedIncidentDialog.resize(645, 341)
        self.verticalLayout = QtWidgets.QVBoxLayout(continuedIncidentDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(continuedIncidentDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.instructionsLabel = QtWidgets.QLabel(continuedIncidentDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.instructionsLabel.setFont(font)
        self.instructionsLabel.setTextFormat(QtCore.Qt.PlainText)
        self.instructionsLabel.setScaledContents(False)
        self.instructionsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.instructionsLabel.setWordWrap(True)
        self.instructionsLabel.setObjectName("instructionsLabel")
        self.horizontalLayout_2.addWidget(self.instructionsLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 10)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.theTable = QtWidgets.QTableWidget(continuedIncidentDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.theTable.setFont(font)
        self.theTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.theTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.theTable.setShowGrid(True)
        self.theTable.setObjectName("theTable")
        self.theTable.setColumnCount(4)
        self.theTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.theTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.theTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.theTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.theTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.theTable.setHorizontalHeaderItem(3, item)
        self.theTable.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.theTable)
        self.yesButton = QtWidgets.QPushButton(continuedIncidentDialog)
        self.yesButton.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.yesButton.setFont(font)
        self.yesButton.setObjectName("yesButton")
        self.verticalLayout.addWidget(self.yesButton)
        self.noButton = QtWidgets.QPushButton(continuedIncidentDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.noButton.setFont(font)
        self.noButton.setDefault(True)
        self.noButton.setObjectName("noButton")
        self.verticalLayout.addWidget(self.noButton)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(continuedIncidentDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 20)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(continuedIncidentDialog)
        self.yesButton.clicked.connect(continuedIncidentDialog.accept) # type: ignore
        self.noButton.clicked.connect(continuedIncidentDialog.reject) # type: ignore
        self.theTable.cellClicked['int','int'].connect(continuedIncidentDialog.cellClicked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(continuedIncidentDialog)

    def retranslateUi(self, continuedIncidentDialog):
        _translate = QtCore.QCoreApplication.translate
        continuedIncidentDialog.setWindowTitle(_translate("continuedIncidentDialog", "Continued Incident"))
        self.label.setText(_translate("continuedIncidentDialog", "Is this a Continued Incident?"))
        self.instructionsLabel.setText(_translate("continuedIncidentDialog", "If so, select a row from the following list of radiolog sessions that were run on this computer within the last n days, then click YES."))
        item = self.theTable.verticalHeaderItem(0)
        item.setText(_translate("continuedIncidentDialog", "New Row"))
        item = self.theTable.horizontalHeaderItem(0)
        item.setText(_translate("continuedIncidentDialog", "Incident Name"))
        item = self.theTable.horizontalHeaderItem(1)
        item.setText(_translate("continuedIncidentDialog", "Last OP"))
        item = self.theTable.horizontalHeaderItem(2)
        item.setText(_translate("continuedIncidentDialog", "Last Clue"))
        item = self.theTable.horizontalHeaderItem(3)
        item.setText(_translate("continuedIncidentDialog", "Last Edited"))
        self.yesButton.setText(_translate("continuedIncidentDialog", "YES:  Start a new OP of \'Continued Incident\'\n"
"(OP = n+1; next clue# = i+1)"))
        self.noButton.setText(_translate("continuedIncidentDialog", "NO:  Start a New Incident\n"
"(OP = 1; next clue# = 1)"))
        self.label_3.setText(_translate("continuedIncidentDialog", "- Incident Name can be changed at any time from the Options dialog.\n"
"- OP# can be changed at any time from the OP button at the top left of the main radiolog window.\n"
"- Clue# can be changed from the Clue Dialog during a new entry; subsequent clue numbers always increment."))
