# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\caver\Documents\GitHub\radiolog\designer\findPopup.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_findPopup(object):
    def setupUi(self, findPopup):
        findPopup.setObjectName("findPopup")
        findPopup.resize(339, 31)
        self.findField = QtWidgets.QLineEdit(findPopup)
        self.findField.setGeometry(QtCore.QRect(0, 0, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.findField.setFont(font)
        self.findField.setObjectName("findField")

        self.retranslateUi(findPopup)
        QtCore.QMetaObject.connectSlotsByName(findPopup)

    def retranslateUi(self, findPopup):
        _translate = QtCore.QCoreApplication.translate
        findPopup.setWindowTitle(_translate("findPopup", "Find"))
        self.findField.setPlaceholderText(_translate("findPopup", "Enter text to search for..."))
