# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\caver\Documents\GitHub\radiolog\designer\findPopup.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_findPopup(object):
    def setupUi(self, findPopup):
        findPopup.setObjectName("findPopup")
        findPopup.resize(311, 56)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(findPopup.sizePolicy().hasHeightForWidth())
        findPopup.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(findPopup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.findField = QtWidgets.QLineEdit(findPopup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findField.sizePolicy().hasHeightForWidth())
        self.findField.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.findField.setFont(font)
        self.findField.setObjectName("findField")
        self.verticalLayout.addWidget(self.findField)

        self.retranslateUi(findPopup)
        QtCore.QMetaObject.connectSlotsByName(findPopup)

    def retranslateUi(self, findPopup):
        _translate = QtCore.QCoreApplication.translate
        findPopup.setWindowTitle(_translate("findPopup", "Find"))
        self.findField.setPlaceholderText(_translate("findPopup", "Enter text to search for..."))
