# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\caver\Documents\GitHub\radiolog\designer\findDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_findDialog(object):
    def setupUi(self, findDialog):
        findDialog.setObjectName("findDialog")
        findDialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(findDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.findField = QtWidgets.QLineEdit(findDialog)
        self.findField.setGeometry(QtCore.QRect(30, 80, 321, 22))
        self.findField.setObjectName("findField")

        self.retranslateUi(findDialog)
        self.buttonBox.accepted.connect(findDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(findDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(findDialog)

    def retranslateUi(self, findDialog):
        _translate = QtCore.QCoreApplication.translate
        findDialog.setWindowTitle(_translate("findDialog", "Find"))
