# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fsSendMessageDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fsSendMessageDialog(object):
    def setupUi(self, fsSendMessageDialog):
        fsSendMessageDialog.setObjectName("fsSendMessageDialog")
        fsSendMessageDialog.resize(404, 139)
        self.verticalLayout = QtWidgets.QVBoxLayout(fsSendMessageDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.theLabel = QtWidgets.QLabel(fsSendMessageDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.theLabel.setFont(font)
        self.theLabel.setStyleSheet("margin-bottom:5px")
        self.theLabel.setWordWrap(True)
        self.theLabel.setObjectName("theLabel")
        self.verticalLayout_4.addWidget(self.theLabel)
        self.label_4 = QtWidgets.QLabel(fsSendMessageDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.messageField = QtWidgets.QLineEdit(fsSendMessageDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.messageField.setFont(font)
        self.messageField.setObjectName("messageField")
        self.verticalLayout_4.addWidget(self.messageField)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.buttonBox = QtWidgets.QDialogButtonBox(fsSendMessageDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.buttonBox.setFont(font)
        self.buttonBox.setStyleSheet("button-layout:2;")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(fsSendMessageDialog)
        self.buttonBox.accepted.connect(fsSendMessageDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(fsSendMessageDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(fsSendMessageDialog)

    def retranslateUi(self, fsSendMessageDialog):
        _translate = QtCore.QCoreApplication.translate
        fsSendMessageDialog.setWindowTitle(_translate("fsSendMessageDialog", "FleetSync Send Message"))
        self.theLabel.setText(_translate("fsSendMessageDialog", "Message"))
        self.label_4.setText(_translate("fsSendMessageDialog", " 36 characters max; date and time automatically included"))
