# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\caver\Documents\GitHub\radiolog\designer\loadDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loadDialog(object):
    def setupUi(self, loadDialog):
        loadDialog.setObjectName("loadDialog")
        loadDialog.resize(823, 502)
        self.verticalLayout = QtWidgets.QVBoxLayout(loadDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(loadDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.theTable = QtWidgets.QTableWidget(loadDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.theTable.sizePolicy().hasHeightForWidth())
        self.theTable.setSizePolicy(sizePolicy)
        self.theTable.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.theTable.setFont(font)
        self.theTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.theTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.theTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.theTable.setShowGrid(True)
        self.theTable.setCornerButtonEnabled(False)
        self.theTable.setObjectName("theTable")
        self.theTable.setColumnCount(4)
        self.theTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.theTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.theTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.theTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.theTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.theTable.setHorizontalHeaderItem(3, item)
        self.theTable.horizontalHeader().setHighlightSections(False)
        self.theTable.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.theTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(loadDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.buttonBox = QtWidgets.QDialogButtonBox(loadDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.buttonBox.setFont(font)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(loadDialog)
        self.theTable.cellClicked['int','int'].connect(loadDialog.cellClicked) # type: ignore
        self.buttonBox.accepted.connect(loadDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(loadDialog.reject) # type: ignore
        self.pushButton.clicked.connect(loadDialog.useBrowserClicked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(loadDialog)

    def retranslateUi(self, loadDialog):
        _translate = QtCore.QCoreApplication.translate
        loadDialog.setWindowTitle(_translate("loadDialog", "Load"))
        self.label.setText(_translate("loadDialog", "Select a session to load:"))
        item = self.theTable.verticalHeaderItem(0)
        item.setText(_translate("loadDialog", "New Row"))
        item = self.theTable.horizontalHeaderItem(0)
        item.setText(_translate("loadDialog", "Incident Name"))
        item = self.theTable.horizontalHeaderItem(1)
        item.setText(_translate("loadDialog", "Last OP"))
        item = self.theTable.horizontalHeaderItem(2)
        item.setText(_translate("loadDialog", "Last Clue"))
        item = self.theTable.horizontalHeaderItem(3)
        item.setText(_translate("loadDialog", "Last Edited"))
        self.pushButton.setText(_translate("loadDialog", "Use Browser"))
