# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\caver\Documents\GitHub\radiolog\designer\loginDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginDialog(object):
    def setupUi(self, loginDialog):
        loginDialog.setObjectName("loginDialog")
        loginDialog.resize(527, 362)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        loginDialog.setFont(font)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(loginDialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.knownGroupBox = QtWidgets.QGroupBox(loginDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.knownGroupBox.setFont(font)
        self.knownGroupBox.setStyleSheet("QGroupBox{\n"
"    border:1px solid darkgray;\n"
"    border-radius:5px;\n"
"    margin-top:10px;\n"
"}\n"
"QGroupBox::title{\n"
"    padding-top:-24px;\n"
"    left:10px;\n"
"}")
        self.knownGroupBox.setObjectName("knownGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.knownGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.knownComboBox = QtWidgets.QComboBox(self.knownGroupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.knownComboBox.setFont(font)
        self.knownComboBox.setObjectName("knownComboBox")
        self.verticalLayout_2.addWidget(self.knownComboBox)
        self.verticalLayout_3.addWidget(self.knownGroupBox)
        self.orLabel = QtWidgets.QLabel(loginDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.orLabel.setFont(font)
        self.orLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.orLabel.setObjectName("orLabel")
        self.verticalLayout_3.addWidget(self.orLabel)
        self.firstTimeGroupBox = QtWidgets.QGroupBox(loginDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.firstTimeGroupBox.setFont(font)
        self.firstTimeGroupBox.setStyleSheet("QGroupBox{\n"
"    border:1px solid darkgray;\n"
"    border-radius:5px;\n"
"    margin-top:10px;\n"
"}\n"
"QGroupBox::title{\n"
"    padding-top:-24px;\n"
"    left:10px;\n"
"}")
        self.firstTimeGroupBox.setObjectName("firstTimeGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.firstTimeGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lastNameHLayout = QtWidgets.QHBoxLayout()
        self.lastNameHLayout.setObjectName("lastNameHLayout")
        self.lastNameLabel = QtWidgets.QLabel(self.firstTimeGroupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.lastNameLabel.setFont(font)
        self.lastNameLabel.setObjectName("lastNameLabel")
        self.lastNameHLayout.addWidget(self.lastNameLabel)
        self.lastNameField = QtWidgets.QLineEdit(self.firstTimeGroupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.lastNameField.setFont(font)
        self.lastNameField.setObjectName("lastNameField")
        self.lastNameHLayout.addWidget(self.lastNameField)
        self.verticalLayout.addLayout(self.lastNameHLayout)
        self.firstNameHLayout = QtWidgets.QHBoxLayout()
        self.firstNameHLayout.setObjectName("firstNameHLayout")
        self.firstNameLabel = QtWidgets.QLabel(self.firstTimeGroupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.firstNameLabel.setFont(font)
        self.firstNameLabel.setObjectName("firstNameLabel")
        self.firstNameHLayout.addWidget(self.firstNameLabel)
        self.firstNameField = QtWidgets.QLineEdit(self.firstTimeGroupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.firstNameField.setFont(font)
        self.firstNameField.setObjectName("firstNameField")
        self.firstNameHLayout.addWidget(self.firstNameField)
        self.verticalLayout.addLayout(self.firstNameHLayout)
        self.idHLayout = QtWidgets.QHBoxLayout()
        self.idHLayout.setObjectName("idHLayout")
        self.idLabel = QtWidgets.QLabel(self.firstTimeGroupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.idLabel.setFont(font)
        self.idLabel.setObjectName("idLabel")
        self.idHLayout.addWidget(self.idLabel)
        self.idField = QtWidgets.QLineEdit(self.firstTimeGroupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.idField.setFont(font)
        self.idField.setObjectName("idField")
        self.idHLayout.addWidget(self.idField)
        self.verticalLayout.addLayout(self.idHLayout)
        self.verticalLayout_3.addWidget(self.firstTimeGroupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(loginDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(loginDialog)
        self.buttonBox.accepted.connect(loginDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(loginDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(loginDialog)

    def retranslateUi(self, loginDialog):
        _translate = QtCore.QCoreApplication.translate
        loginDialog.setWindowTitle(_translate("loginDialog", "Log In / Change Operator"))
        self.knownGroupBox.setTitle(_translate("loginDialog", "Known Operator"))
        self.orLabel.setText(_translate("loginDialog", "-- OR --"))
        self.firstTimeGroupBox.setTitle(_translate("loginDialog", "First-time Operator"))
        self.lastNameLabel.setText(_translate("loginDialog", "Last Name"))
        self.firstNameLabel.setText(_translate("loginDialog", "First Name"))
        self.idLabel.setText(_translate("loginDialog", "ID (SAR ID, callsign, etc)"))
