# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\caver\Documents\GitHub\radiolog\designer\splash.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_splash(object):
    def setupUi(self, splash):
        splash.setObjectName("splash")
        splash.resize(361, 230)
        self.pushButton = QtWidgets.QPushButton(splash)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(15, 15, 126, 141))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/radiolog_ui/icons/radio.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(200, 200))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(splash)
        self.label.setGeometry(QtCore.QRect(150, 25, 166, 56))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.currentVersionLabel = QtWidgets.QLabel(splash)
        self.currentVersionLabel.setGeometry(QtCore.QRect(170, 80, 136, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.currentVersionLabel.setFont(font)
        self.currentVersionLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.currentVersionLabel.setObjectName("currentVersionLabel")
        self.newVersionLabel = QtWidgets.QLabel(splash)
        self.newVersionLabel.setGeometry(QtCore.QRect(0, 165, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.newVersionLabel.setFont(font)
        self.newVersionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.newVersionLabel.setObjectName("newVersionLabel")
        self.newVersionFooterLabel = QtWidgets.QLabel(splash)
        self.newVersionFooterLabel.setGeometry(QtCore.QRect(0, 190, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.newVersionFooterLabel.setFont(font)
        self.newVersionFooterLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.newVersionFooterLabel.setObjectName("newVersionFooterLabel")
        self.statusLabel = QtWidgets.QLabel(splash)
        self.statusLabel.setGeometry(QtCore.QRect(125, 130, 231, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.statusLabel.setFont(font)
        self.statusLabel.setText("")
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")

        self.retranslateUi(splash)
        QtCore.QMetaObject.connectSlotsByName(splash)

    def retranslateUi(self, splash):
        _translate = QtCore.QCoreApplication.translate
        splash.setWindowTitle(_translate("splash", "RadioLog"))
        self.label.setText(_translate("splash", "RadioLog"))
        self.currentVersionLabel.setText(_translate("splash", "xx.xx.xx"))
        self.newVersionLabel.setText(_translate("splash", "New version available:"))
        self.newVersionFooterLabel.setText(_translate("splash", "More information will be shown on exit."))
import radiolog_ui_rc
