# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'subjectLocatedDialog.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_subjectLocatedDialog(object):
    def setupUi(self, subjectLocatedDialog):
        subjectLocatedDialog.setObjectName("subjectLocatedDialog")
        subjectLocatedDialog.resize(728, 628)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        subjectLocatedDialog.setFont(font)
        self.label_4 = QtWidgets.QLabel(subjectLocatedDialog)
        self.label_4.setGeometry(QtCore.QRect(10, 340, 131, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.buttonBox = QtWidgets.QDialogButtonBox(subjectLocatedDialog)
        self.buttonBox.setGeometry(QtCore.QRect(490, 570, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_3 = QtWidgets.QLabel(subjectLocatedDialog)
        self.label_3.setGeometry(QtCore.QRect(10, 160, 131, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(subjectLocatedDialog)
        self.label.setGeometry(QtCore.QRect(10, 220, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.locationField = QtWidgets.QLineEdit(subjectLocatedDialog)
        self.locationField.setGeometry(QtCore.QRect(150, 160, 561, 39))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.locationField.setFont(font)
        self.locationField.setObjectName("locationField")
        self.label_2 = QtWidgets.QLabel(subjectLocatedDialog)
        self.label_2.setGeometry(QtCore.QRect(220, 10, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(subjectLocatedDialog)
        self.groupBox.setGeometry(QtCore.QRect(30, 60, 661, 81))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioLocField = QtWidgets.QLineEdit(self.groupBox)
        self.radioLocField.setEnabled(False)
        self.radioLocField.setGeometry(QtCore.QRect(420, 20, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.radioLocField.setFont(font)
        self.radioLocField.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioLocField.setText("")
        self.radioLocField.setObjectName("radioLocField")
        self.callsignField = QtWidgets.QLineEdit(self.groupBox)
        self.callsignField.setEnabled(False)
        self.callsignField.setGeometry(QtCore.QRect(240, 20, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.callsignField.setFont(font)
        self.callsignField.setFocusPolicy(QtCore.Qt.NoFocus)
        self.callsignField.setText("")
        self.callsignField.setObjectName("callsignField")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setEnabled(False)
        self.label_5.setGeometry(QtCore.QRect(240, 40, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setEnabled(False)
        self.label_8.setGeometry(QtCore.QRect(420, 40, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setEnabled(False)
        self.label_7.setGeometry(QtCore.QRect(130, 40, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.timeField = QtWidgets.QLineEdit(self.groupBox)
        self.timeField.setEnabled(False)
        self.timeField.setGeometry(QtCore.QRect(130, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.timeField.setFont(font)
        self.timeField.setFocusPolicy(QtCore.Qt.NoFocus)
        self.timeField.setText("")
        self.timeField.setObjectName("timeField")
        self.dateField = QtWidgets.QLineEdit(self.groupBox)
        self.dateField.setEnabled(False)
        self.dateField.setGeometry(QtCore.QRect(20, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.dateField.setFont(font)
        self.dateField.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dateField.setText("")
        self.dateField.setObjectName("dateField")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setEnabled(False)
        self.label_9.setGeometry(QtCore.QRect(20, 40, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.conditionField = QtWidgets.QPlainTextEdit(subjectLocatedDialog)
        self.conditionField.setGeometry(QtCore.QRect(150, 220, 561, 101))
        self.conditionField.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.conditionField.setMouseTracking(True)
        self.conditionField.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.conditionField.setStyleSheet("font: 14pt \"Segoe UI\";")
        self.conditionField.setInputMethodHints(QtCore.Qt.ImhNone)
        self.conditionField.setTabChangesFocus(True)
        self.conditionField.setPlainText("")
        self.conditionField.setObjectName("conditionField")
        self.resourcesField = QtWidgets.QPlainTextEdit(subjectLocatedDialog)
        self.resourcesField.setGeometry(QtCore.QRect(150, 340, 561, 101))
        self.resourcesField.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.resourcesField.setMouseTracking(True)
        self.resourcesField.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.resourcesField.setStyleSheet("font: 14pt \"Segoe UI\";")
        self.resourcesField.setInputMethodHints(QtCore.Qt.ImhNone)
        self.resourcesField.setTabChangesFocus(True)
        self.resourcesField.setObjectName("resourcesField")
        self.otherField = QtWidgets.QPlainTextEdit(subjectLocatedDialog)
        self.otherField.setGeometry(QtCore.QRect(150, 460, 561, 101))
        self.otherField.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.otherField.setMouseTracking(True)
        self.otherField.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.otherField.setStyleSheet("font: 14pt \"Segoe UI\";")
        self.otherField.setInputMethodHints(QtCore.Qt.ImhNone)
        self.otherField.setTabChangesFocus(True)
        self.otherField.setObjectName("otherField")
        self.label_6 = QtWidgets.QLabel(subjectLocatedDialog)
        self.label_6.setGeometry(QtCore.QRect(10, 460, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.groupBox.raise_()
        self.label_4.raise_()
        self.buttonBox.raise_()
        self.label_3.raise_()
        self.label.raise_()
        self.locationField.raise_()
        self.label_2.raise_()
        self.conditionField.raise_()
        self.resourcesField.raise_()
        self.otherField.raise_()
        self.label_6.raise_()

        self.retranslateUi(subjectLocatedDialog)
        self.buttonBox.accepted.connect(subjectLocatedDialog.accept)
        self.buttonBox.rejected.connect(subjectLocatedDialog.close)
        QtCore.QMetaObject.connectSlotsByName(subjectLocatedDialog)
        subjectLocatedDialog.setTabOrder(self.locationField, self.conditionField)
        subjectLocatedDialog.setTabOrder(self.conditionField, self.resourcesField)
        subjectLocatedDialog.setTabOrder(self.resourcesField, self.otherField)

    def retranslateUi(self, subjectLocatedDialog):
        _translate = QtCore.QCoreApplication.translate
        subjectLocatedDialog.setWindowTitle(_translate("subjectLocatedDialog", "Subject Located"))
        self.label_4.setText(_translate("subjectLocatedDialog", "Resources Needed"))
        self.label_3.setText(_translate("subjectLocatedDialog", "Location"))
        self.label.setText(_translate("subjectLocatedDialog", "Condition"))
        self.label_2.setText(_translate("subjectLocatedDialog", "Subject Located"))
        self.label_5.setText(_translate("subjectLocatedDialog", "REPORTED BY"))
        self.label_8.setText(_translate("subjectLocatedDialog", "RADIO LOCATION"))
        self.label_7.setText(_translate("subjectLocatedDialog", "TIME"))
        self.label_9.setText(_translate("subjectLocatedDialog", "DATE"))
        self.label_6.setText(_translate("subjectLocatedDialog", "Other"))

