# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\caver\Documents\GitHub\radiolog\designer\teamTabsPopup.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_teamTabsPopup(object):
    def setupUi(self, teamTabsPopup):
        teamTabsPopup.setObjectName("teamTabsPopup")
        teamTabsPopup.resize(525, 805)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        teamTabsPopup.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(teamTabsPopup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.teamTabsTableWidget = QtWidgets.QTableWidget(teamTabsPopup)
        self.teamTabsTableWidget.setObjectName("teamTabsTableWidget")
        self.teamTabsTableWidget.setColumnCount(0)
        self.teamTabsTableWidget.setRowCount(0)
        self.teamTabsTableWidget.horizontalHeader().setVisible(False)
        self.teamTabsTableWidget.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.teamTabsTableWidget)
        self.teamTabsSummaryTableWidget = QtWidgets.QTableWidget(teamTabsPopup)
        self.teamTabsSummaryTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.teamTabsSummaryTableWidget.setObjectName("teamTabsSummaryTableWidget")
        self.teamTabsSummaryTableWidget.setColumnCount(7)
        self.teamTabsSummaryTableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.teamTabsSummaryTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.teamTabsSummaryTableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.teamTabsSummaryTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.teamTabsSummaryTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.teamTabsSummaryTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.teamTabsSummaryTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.teamTabsSummaryTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.teamTabsSummaryTableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.teamTabsSummaryTableWidget.setHorizontalHeaderItem(6, item)
        self.verticalLayout.addWidget(self.teamTabsSummaryTableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(teamTabsPopup)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(teamTabsPopup)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.pushButton = QtWidgets.QPushButton(teamTabsPopup)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(teamTabsPopup)
        QtCore.QMetaObject.connectSlotsByName(teamTabsPopup)

    def retranslateUi(self, teamTabsPopup):
        _translate = QtCore.QCoreApplication.translate
        teamTabsPopup.setWindowTitle(_translate("teamTabsPopup", "Form"))
        item = self.teamTabsSummaryTableWidget.verticalHeaderItem(0)
        item.setText(_translate("teamTabsPopup", "Teams"))
        item = self.teamTabsSummaryTableWidget.verticalHeaderItem(1)
        item.setText(_translate("teamTabsPopup", "Total"))
        item = self.teamTabsSummaryTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("teamTabsPopup", "At IC"))
        item = self.teamTabsSummaryTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("teamTabsPopup", "In Transit"))
        item = self.teamTabsSummaryTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("teamTabsPopup", "Working"))
        item = self.teamTabsSummaryTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("teamTabsPopup", "Waiting for Transport"))
        item = self.teamTabsSummaryTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("teamTabsPopup", "STANDBY"))
        item = self.teamTabsSummaryTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("teamTabsPopup", "Available"))
        item = self.teamTabsSummaryTableWidget.horizontalHeaderItem(6)
        item.setText(_translate("teamTabsPopup", "Off Duty"))
        self.label.setText(_translate("teamTabsPopup", "Hidden tabs:"))
        self.pushButton.setText(_translate("teamTabsPopup", "Unhide"))
