# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\caver\Documents\GitHub\radiolog\designer\teamNotesDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_teamNotesDialog(object):
    def setupUi(self, teamNotesDialog):
        teamNotesDialog.setObjectName("teamNotesDialog")
        teamNotesDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(teamNotesDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.teamLabel = QtWidgets.QLabel(teamNotesDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teamLabel.sizePolicy().hasHeightForWidth())
        self.teamLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.teamLabel.setFont(font)
        self.teamLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.teamLabel.setObjectName("teamLabel")
        self.horizontalLayout.addWidget(self.teamLabel)
        self.teamField = QtWidgets.QComboBox(teamNotesDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.teamField.setFont(font)
        self.teamField.setObjectName("teamField")
        self.horizontalLayout.addWidget(self.teamField)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.notesField = QtWidgets.QPlainTextEdit(teamNotesDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.notesField.setFont(font)
        self.notesField.setObjectName("notesField")
        self.verticalLayout.addWidget(self.notesField)
        self.buttonBox = QtWidgets.QDialogButtonBox(teamNotesDialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(teamNotesDialog)
        self.buttonBox.accepted.connect(teamNotesDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(teamNotesDialog.reject) # type: ignore
        self.teamField.currentTextChanged['QString'].connect(teamNotesDialog.teamChanged) # type: ignore
        self.notesField.textChanged.connect(teamNotesDialog.notesTextChanged) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(teamNotesDialog)

    def retranslateUi(self, teamNotesDialog):
        _translate = QtCore.QCoreApplication.translate
        teamNotesDialog.setWindowTitle(_translate("teamNotesDialog", "Team Notes"))
        self.teamLabel.setText(_translate("teamNotesDialog", "View / edit notes for"))
